### ISSUE TITLE
Missing error handling on form submit 

### ISSUE THREAD

**Issue by twojtylak** [mautic/mautic-typo3#48]
If there is an error when submitting a form, it is currently not handled.
At this point, mautic (unfortunately) returns a response with the status code 302 and would like to redirect to the current page with  the query argument `?mauticError`. E.g.:

` Redirecting to <a href="https://www.typo3-mautic.de/gewinnspiel-typo3-mautic/?mauticError=Fehler%3A%3Cbr%20%2F%3E%3Col%3E%3Cli%3E%27Geburtstag%27%20ist%20erforderlich.%3C%2Fli%3E%3C%2Fol%3E#gewinnspiel">https://www.typo3-mautic.de/gewinnspiel-typo3-mautic/?mauticError=Fehler%3A%3Cbr%20%2F%3E%3Col%3E%3Cli%3E%27Geburtstag%27%20ist%20erforderlich.%3C%2Fli%3E%3C%2Fol%3E#gewinnspiel</a>.
`

In the FormRepository, however, it is only checked whether the HTTP-Status-Code is `< 200 | >= 400` and only in this case logs an error (if the logging for production was overwritten)

**Expected behavior**
The error should at least be logged or, even better, an error message should be displayed for the user.

**Comment by ekkeguembel** [comment]
Hmm, tricky - a 30x is not an error but can be expected behavior, e.g. if you set the "Successful Submit Action" in Mautic to "Redirect URL".
We're currently trying to add a "form submit" action to the Mautic API, at that point your issue should be history...
Until then, I guess it'*s best to simply avoid the error by having the same field validation in TYPO3 as you have in Mautic.
