### ISSUE TITLE
Determining the personas of a visitor is incomplete

### ISSUE THREAD

**Issue by rbtwt** [mautic/mautic-typo3#63]
**Describe the bug**
A contact belongs to two mautic segments (Segment1, Segment2).
Each mautic segment defines a persona in Typo3 (Persona1=>Segment1, Persona2=>Segment2).
Only one persona is determined by the findBySegments method in the PersonaRepository (e.g. Persona1).
Content elements configured for Persona2 are not displayed to the contact, even though he belongs to this persona.

**Expected behavior**
The contact sees content elements for each persona he belongs to.

**Question**
Do I miss something here? Is this not a valid use case?

**Comment by ekkeguembel** [comment]
Hi @rbtwt , this is indeed the expected behavior - and the reason why we are calling this "persona", not work with "segment" directly.
One typical use case behind that is: There is _one_ slot in the layout that shall be used appropriately. Thus only _one_ match is wanted.
(We did discuss an optional setting to change of that behavior, but never implemented this)
