### ISSUE TITLE
Hide a content item if the user does not belong to a specific persona

### ISSUE THREAD

**Issue by rbtwt** [mautic/mautic-typo3#65]
**Is your feature request related to a problem? Please describe.**
How can I configure a content item to only display if the user does not belong to a specific persona?
Currently, there doesn't seem to be a way to do this.

The use case would be to display a form element only if the user does not belong to the "Prospects" persona. However, the user could/could be in other personas.
Submitting the form would move the contact to the "Prospects" segment (within Mautic) and thus to the "Prospects" persona.
When he visits the page again, he would no longer see the form.

**Comment by ekkeguembel** [comment]
Thanks for the suggestion, we added this as a feature idea.

_Background:_
The idea behind "personas" is that they are a stable and distinct, and a much smaller number than segments - thus if there are only e.g. 5 personas, you can easily say "one out of these 4" rather than "not that one".
I understand that your situation may be different, so again: Possible future enhancement!
