### ISSUE TITLE
Mautic connection lost after time

### ISSUE THREAD

**Issue by KreativeKrise** [mautic/mautic-typo3#75]
Mautic was successfully connected via the REST API. However, after a while, before editing forms or calling the file list, you always seem to have to open the "API Connection" menu item once.

Otherwise, when editing the form, you only get "None" as an option when selecting the Mautic Property Type.

Also the file storage cannot be accessed.

I guess that the access token did expire. How do you handle this?

Is this the intended behavior or do I need to configure something else?

**Comment by ekkeguembel** [comment]
Issue confirmed, obviously is a glitch in the changes in the OAuth2 part. Thanks for reporting & please hold the line!

**Comment by Moongazer** [comment]
@KreativeKrise Should we discuss a proper solution for this issue? I'm not very experienced with API authentications, but from my understanding we just need to check the validity of the current access-token BEFORE each API request.

The `MauticAuthorizeService` has two very similar methods for this: `validateAccessToken()` and `accessTokenToBeRefreshed()`. Both relying on the `expires` value, which is probably the easiest but not the best solution (e.g. if the access-token is revoked on Mautic side, these checks will fail). But because this is an edge-case, I think it's fine to just renew the token if it is expired.

Question: where does it makes sense to check the access-token?

Maybe a good place is `AbstractRepository::__construct()`, to make sure the token is validated before each API request. Or is it better to place the check inside `AuthorizationFactory::createAuthorizationFromExtensionConfiguration()`?

Any input appreciated.

**Comment by KreativeKrise** [comment]
@Moongazer I'm no developer, so I have no idea what's the best way to solve this issue. But your suggestion sounds reasonable.
